### ISSUE TITLE
Should feature.xml require `org.eclipse.pde` ?

### ISSUE THREAD

**Issue by paulvi** [jeeeyul/pde-tools#40]
https://github.com/jeeeyul/pde-tools/blob/master/net.jeeeyul.pdetools.feature/feature.xml

Should feature.xml require `org.eclipse.pde` ?

That would install PDE if not installed

**Comment by jeeeyul** [comment]
Yes it needs PDE plugin.
Image Constant Generation feature needs that.

**Comment by paulvi** [comment]
ref #33
